"""zij: a library of deep learning optimizers."""

from .contrib.first_order import (
    ADOPT,
    FOCUS,
    LARS,
    MADGRAD,
    MARS,
    PID,
    QHM,
    SGDP,
    SWATS,
    A2GradExp,
    A2GradInc,
    A2GradUni,
    AccSGD,
    AdaBelief,
    AdaBound,
    AdaBoundW,
    AdaGC,
    Adai,
    AdamAtan2,
    AdaMod,
    AdamP,
    Adan,
    AdaNorm,
    AdaPNM,
    AdaShift,
    AdaSmooth,
    AdEMAMix,
    AggMo,
    Amos,
    AvaGrad,
    DiffGrad,
    EXAdam,
    FAdam,
    Grams,
    Gravity,
    KourkoutasSoftmaxFlex,
    Lamb,
    LaProp,
    Lion,
    Lookahead,
    MirrorMADGRAD,
    NovoGrad,
    PAdam,
    QHAdam,
    Ranger,
    Ranger21,
    SGDSaI,
    SignSGD,
    StableAdamW,
    Tiger,
    Yogi,
)
from .contrib.lr_free import (
    TRAC,
    AdamG,
    AdamWScheduleFree,
    DAdaptAdam,
    DAdaptSGD,
    DoG,
    LDoG,
    Momo,
    MomoAdam,
    Prodigy,
    RAdamScheduleFree,
    ScheduleFreeWrapper,
    SGDScheduleFree,
    is_mechanized,
    mechanize,
)
from .contrib.memory_efficient import (
    APOLLO,
    CAME,
    SM3,
    SPAM,
    AdaLomo,
    AdamMini,
    BlockOptimizer,
    BlockOptimizerRatio,
    FiraAdamW,
    GaLoreAdamW,
    GrokAdamW,
    LDAdamW,
    Lomo,
)
from .contrib.second_order import (
    SOAP,
    Adahessian,
    AdaMuon,
    NorMuon,
    NorMuonWithAuxAdam,
    PolarGrad,
    Scion,
    Shampoo,
    SingleDeviceNorMuon,
    SingleDeviceNorMuonWithAuxAdam,
    SophiaG,
    SPlus,
)
from .contrib.sharpness_aware import (
    ASAM,
    GSAM,
    SAM,
    WSAM,
    LookSAM,
    ProportionScheduler,
)
from .core import (
    ASGD,
    LBFGS,
    SGD,
    Adadelta,
    Adafactor,
    Adagrad,
    Adam,
    Adamax,
    AdamW,
    Muon,
    NAdam,
    Optimizer,
    RAdam,
    RMSprop,
    Rprop,
    SparseAdam,
    lr_scheduler,
    swa_utils,
)
from .registry import (
    _register,
    construction_of,
    list_optimizers,
    load_optimizer,
)

__version__ = "0.1.1"

for _cls in (
    Adafactor,
    Adadelta,
    Adagrad,
    Adam,
    Adamax,
    AdamW,
    ASGD,
    LBFGS,
    Muon,
    NAdam,
    RAdam,
    RMSprop,
    Rprop,
    SGD,
    SparseAdam,
    AdamG,
    AdamWScheduleFree,
    DAdaptAdam,
    DAdaptSGD,
    DoG,
    LDoG,
    Momo,
    MomoAdam,
    Prodigy,
    RAdamScheduleFree,
    SGDScheduleFree,
    ASAM,
    GSAM,
    LookSAM,
    SAM,
    WSAM,
    APOLLO,
    CAME,
    SM3,
    SPAM,
    FiraAdamW,
    GaLoreAdamW,
    GrokAdamW,
    LDAdamW,
    ADOPT,
    AdaBelief,
    AdaBound,
    AdaBoundW,
    AdamP,
    Adan,
    AdEMAMix,
    DiffGrad,
    Grams,
    LaProp,
    Lion,
    MADGRAD,
    MARS,
    MirrorMADGRAD,
    QHAdam,
    QHM,
    SGDP,
    Yogi,
    A2GradExp,
    A2GradInc,
    A2GradUni,
    AccSGD,
    AggMo,
    AvaGrad,
    Lamb,
    LARS,
    NovoGrad,
    PID,
    Ranger,
    Ranger21,
    StableAdamW,
    SWATS,
    Tiger,
    SOAP,
    Shampoo,
    Adai,
    AdaMod,
    AdamAtan2,
    EXAdam,
    FAdam,
    AdaMuon,
    Scion,
    SophiaG,
    SPlus,
    AdaPNM,
    FOCUS,
    KourkoutasSoftmaxFlex,
    SGDSaI,
    PolarGrad,
    AdaGC,
    AdaNorm,
    AdaShift,
    AdaSmooth,
    Amos,
    Gravity,
    PAdam,
    SignSGD,
):
    _register(_cls)
del _cls

# NorMuon's single-device variant under the friendly name; the distributed
# NorMuon and the WithAuxAdam variants stay importable for explicit use.
_register(SingleDeviceNorMuon, name="normuon")

_register(mechanize(SGD), name="mechanic")

# Optimizers constructed from a model (they read parameter names) or that wrap a
# base optimizer with block structure. Discoverable via list_optimizers(); their
# construction protocol is documented in each class docstring.
_register(AdamMini, construction="model")
_register(Lomo, construction="model")
_register(AdaLomo, construction="model")
_register(BlockOptimizer, construction="wrapper")
_register(Lookahead, construction="wrapper")
_register(TRAC, construction="wrapper")
_register(ScheduleFreeWrapper, construction="wrapper")

# Adahessian needs gradients built with create_graph=True for its Hutchinson
# Hessian-trace estimate, so it is driven differently from the params harness.
_register(Adahessian, construction="hessian")

__all__ = [
    "Adafactor",
    "Adadelta",
    "Adagrad",
    "Adam",
    "Adamax",
    "AdamW",
    "AdamG",
    "AdamMini",
    "AdamP",
    "AdamWScheduleFree",
    "AdaBelief",
    "AdaBound",
    "AdaBoundW",
    "AdaLomo",
    "Adan",
    "AdEMAMix",
    "ADOPT",
    "APOLLO",
    "ASAM",
    "ASGD",
    "BlockOptimizer",
    "BlockOptimizerRatio",
    "CAME",
    "DAdaptAdam",
    "DAdaptSGD",
    "DiffGrad",
    "DoG",
    "FiraAdamW",
    "GaLoreAdamW",
    "Grams",
    "GrokAdamW",
    "GSAM",
    "LaProp",
    "LDAdamW",
    "LDoG",
    "LBFGS",
    "Lion",
    "Lomo",
    "MADGRAD",
    "MARS",
    "MirrorMADGRAD",
    "LookSAM",
    "lr_scheduler",
    "Momo",
    "MomoAdam",
    "Muon",
    "NAdam",
    "Optimizer",
    "Prodigy",
    "ProportionScheduler",
    "QHAdam",
    "QHM",
    "RAdam",
    "RAdamScheduleFree",
    "RMSprop",
    "Rprop",
    "SAM",
    "SGD",
    "SGDP",
    "SGDScheduleFree",
    "SM3",
    "SPAM",
    "SparseAdam",
    "Yogi",
    "swa_utils",
    "WSAM",
    "A2GradExp",
    "A2GradInc",
    "A2GradUni",
    "AccSGD",
    "Adahessian",
    "AdaGC",
    "Adai",
    "AdaMod",
    "AdamAtan2",
    "AdaMuon",
    "AdaNorm",
    "AdaPNM",
    "AdaShift",
    "AdaSmooth",
    "AggMo",
    "Amos",
    "AvaGrad",
    "EXAdam",
    "FAdam",
    "FOCUS",
    "Gravity",
    "KourkoutasSoftmaxFlex",
    "Lamb",
    "LARS",
    "Lookahead",
    "NorMuon",
    "NorMuonWithAuxAdam",
    "NovoGrad",
    "PAdam",
    "PID",
    "PolarGrad",
    "Ranger",
    "Ranger21",
    "ScheduleFreeWrapper",
    "Scion",
    "SGDSaI",
    "Shampoo",
    "SignSGD",
    "SingleDeviceNorMuon",
    "SingleDeviceNorMuonWithAuxAdam",
    "SOAP",
    "SophiaG",
    "SPlus",
    "StableAdamW",
    "SWATS",
    "Tiger",
    "TRAC",
    "construction_of",
    "is_mechanized",
    "list_optimizers",
    "load_optimizer",
    "mechanize",
    "optim",
]

# Imported last so it can mirror the fully-populated namespace; enables
# zij.optim.AdamW alongside zij.AdamW.
from . import optim  # noqa: E402, F401
